general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    path = ~/wayland/walls/nasa.png
    blur_passes = 2
    blur_size = 5
    brightness = 0.8
    vibrancy = 0.2
}

label {
    text = $TIME
    color = rgb(ebdbb2)
    font_size = 85
    font_family = MartianMono NFM Cond Med
    position = 0, -130
    halign = center
    valign = top
}

animations {
    enabled = true
    bezier = instant, 0.0, 0.0, 1.0, 1.0
    bezier = snappy, 0.2, 1.0, 0.4, 1.0
    animation = fadeIn,  1, 4, snappy
    animation = fadeOut, 1, 4, snappy
    animation = inputFieldColors, 1, 2, instant
}

label {
    text = cmd[update:60000] date +"%d-%m-%Y"
    color = rgb(a89984)
    font_size = 16
    font_family = MartianMono NFM Cond Med
    position = 0, -80
    halign = center
    valign = top
}

label {
    text = $LAYOUT[EN,RU]
    color = rgb(b8bb26)
    font_size = 14
    font_family = MartianMono NFM Cond Med
    position = 0, -30
    halign = center
    valign = center
}

input-field {
    size = 200, 45
    outline_thickness = 2
    outer_color = rgb(98971a)
    inner_color = rgba(40, 40, 40, 0.8)
    font_color = rgb(ebdbb2)
    font_family = MartianMono NFM Cond Med
    fade_on_empty = false
    placeholder_text = <span foreground="##a89984"> π </span>
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    position = 0, 30
    halign = center
    valign = center
    rounding = 8
    fail_color = rgb(cc241d)
    fail_text = incorrect
}

auth {
    pam:enabled = true
    pam:module = hyprlock
    fingerprint:enabled = true
    fingerprint:ready_message =  fingerprint
    fingerprint:present_message = loading
}
